### ISSUE TITLE
ignoring comment blocks

### ISSUE THREAD

**Issue by fastriker** [ComSys-OVGU/moodle-quiz-md2xml#3]
I noticed that also comment blocks are processed with the script. In my opinion it is better to ignore comments except they are for inline configuration.

**Comment by mesut-guenes** [comment]
Hi,

Comments should be ignored.
If you use comments for configuration, how to differentiate?


Best,

Mesut Güneş

-------
Univ.-Prof. Dr. Mesut Güneş                   | ***@***.******@***.***>
Chair for Communication and Networked Systems | www.comsys.ovgu.de<http://www.comsys.ovgu.de>
Institute for Intelligent Cooperating Systems |
Otto-von-Guericke-University Magdeburg        | Tel: +49 391 67 57152
Universitätsplatz 2                           |
39106 Magdeburg                               |
-------

On 26. Jul 2021, at 14:48, Kai ***@***.******@***.***>> wrote:



I noticed that also comment blocks are processed with the script. In my opinion it is better to ignore comments except they are for inline configuration.

**Comment by fastriker** [comment]
After discussion with @jmgraeffe in a online meeting: 

1. it is about HTML comments
2. including comments is wanted and a feature
3. the real problem is, that whole questions that are commented out are processed and this in a somehow wrong way

This issue needs further investigation.

**Comment by jmgraeffe** [comment]
Fixed in 3955a71. The changes required small changes to the syntax:

- inline configuration key-value pairs
    - must not be in a HTML comment block
    - are rendered to nothing now

So please update your Markdown files by replacing `<!-- ` and ` -->` with nothing.

---

> including comments is wanted and a feature

I removed that feature since it's probably rarely useful and keeping that feature would make ignoring HTML comments a lot harder, if not impossible without additional syntax.
